### PR TITLE
Add -add-preambles option

### PR DESCRIPTION
**Pull request by satos---jp**
With `-add-preambles` option, the content of `stdlib/preambles.mlw` is automatically appended to the `Preambles` scope.

TODO: Not implemented for why3 plugin.

## How to test

```
$ cat examples/auction_no_header.tzw | head
scope Preambles
  function sum_of : map address mutez -> mutez

  axiom SumE : sum_of (const 0) = 0

  axiom SumI : forall m k v. sum_of m[k <- v] = sum_of m + v - m[k]

  axiom SumN : forall m k. m[k] <= sum_of m

end

$ dune exec -- bin/main.exe examples/auction_no_header.tzw -add-preambles > o.mlw
$ cat o.mlw  | head
module Top
  use export int.Int
  use export int.Abs
  use export int.EuclideanDivision
  use export list.List
  use export option.Option
  use export map.Map
  use export map.Const
  
  exception Insufficient_mutez
```

### CODE REVIEW

**Comment by westpaddy** [comment]
This PR works as intended.
Can you get this working on the plugin, too?
Furthermore, can you get this working if icon is installed as the opam package?

**Comment by westpaddy** [comment]
P.S. The change in RP #10 will break this RP.
I will merge RP #10 first, so could you make this RP following PR #10?

**Comment by satos---jp** [comment]
> This PR works as intended. Can you get this working on the plugin, too? Furthermore, can you get this working if icon is installed as the opam package?

As far as I understand, it seems that why3 plugin does not support parameters passed through the command line, so we need to choose whether to add preambles automatically. If added, existing tzw files will fail with `already defined` error.  (In addition, please let me know if there is good documentation for why3 plugins... I could only find https://www.why3.org/api/Env.html )

**Comment by westpaddy** [comment]
It's enough always to add the preamble. Please delete the overlapped preamble from *.tzw in examples.
Then, the plugin also works as intended, as Gen_mlw.from_mlw returns mlw code containing the added preamble. (The plugin obtains verification condition code from this function.)

A non-trivial task is you cannot refer to `preambles.mlw` by `stdlib/preambles.mlw` when iCon is installed as an OPAM package. A naive solution is embedding the preamble code in the program as strings, but it makes managing the code inconvenient. Could you try to find a better solution? The naive solution can be acceptable, though.

**Comment by westpaddy** [comment]
By the way, there is no good document for implementing a why3 plugin 😅
The document you found and existing implementations, e.g., `plugin/plugin_icon.ml`, are the only clue I know.

**Comment by satos---jp** [comment]
- Added dune rule to generate `preambles.ml`, which contains the string repr of the mlw preamble code, and linked at build time. 

- Now, the preambles are always added automatically, so they are removed from examples.

- The following commands test that the preambles works fine when icon is used as an opam package.
```
$ mkdir test-opam
$ cd test-opam
$ opam switch create .
$ git+https://github.com/satos---jp/icon-why3.git#satos@add-preamble-automatically
$ opam pin add git+https://github.com/satos---jp/icon-why3.git#satos@add-preamble-automatically

$ ##### test Icon.exe #####

$ cat ../icon-why3/examples/boomerang.tzw | head
scope Unknown

  predicate pre (_c : ctx) = true

  predicate post (c : ctx) (c' : ctx) =
    c.boomerang_balance = c'.boomerang_balance

  scope Entrypoint

  predicate default unit


$ icon ../icon-why3/examples/boomerang.tzw | head
module Top
  use export int.Int
  use export int.Abs
  use export int.EuclideanDivision
  use export list.List
  use export option.Option
  use export map.Map
  use export map.Const
  
  exception Insufficient_mutez

$ ##### test why3 plugin #####

$ why3 prove -P z3 ../icon-why3/examples/boomerang.tzw 
File ../icon-why3/examples/boomerang.tzw:
Goal unknown'vc.
Prover result is: Valid (0.01s, 13099 steps).

File ../icon-why3/examples/boomerang.tzw:
Goal boomerang_func'vc.
Prover result is: Valid (0.02s, 20960 steps).
```

**Pull request merged**
